//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:/BME/sem6/onlab/Builds/build_1/CactusLang/Grammar/CactusGrammar.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="ICactusGrammarListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class CactusGrammarBaseListener : ICactusGrammarListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CactusGrammarParser.codefile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCodefile([NotNull] CactusGrammarParser.CodefileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CactusGrammarParser.codefile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCodefile([NotNull] CactusGrammarParser.CodefileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CactusGrammarParser.glob_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterGlob_statement([NotNull] CactusGrammarParser.Glob_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CactusGrammarParser.glob_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitGlob_statement([NotNull] CactusGrammarParser.Glob_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CactusGrammarParser.prepoc_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrepoc_statement([NotNull] CactusGrammarParser.Prepoc_statementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CactusGrammarParser.prepoc_statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrepoc_statement([NotNull] CactusGrammarParser.Prepoc_statementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CactusGrammarParser.func_header"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunc_header([NotNull] CactusGrammarParser.Func_headerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CactusGrammarParser.func_header"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunc_header([NotNull] CactusGrammarParser.Func_headerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CactusGrammarParser.func_dcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunc_dcl([NotNull] CactusGrammarParser.Func_dclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CactusGrammarParser.func_dcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunc_dcl([NotNull] CactusGrammarParser.Func_dclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CactusGrammarParser.field_dcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterField_dcl([NotNull] CactusGrammarParser.Field_dclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CactusGrammarParser.field_dcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitField_dcl([NotNull] CactusGrammarParser.Field_dclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CactusGrammarParser.struct_header"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStruct_header([NotNull] CactusGrammarParser.Struct_headerContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CactusGrammarParser.struct_header"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStruct_header([NotNull] CactusGrammarParser.Struct_headerContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CactusGrammarParser.struct_dcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStruct_dcl([NotNull] CactusGrammarParser.Struct_dclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CactusGrammarParser.struct_dcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStruct_dcl([NotNull] CactusGrammarParser.Struct_dclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CactusGrammarParser.code_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCode_body([NotNull] CactusGrammarParser.Code_bodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CactusGrammarParser.code_body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCode_body([NotNull] CactusGrammarParser.Code_bodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CactusGrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] CactusGrammarParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CactusGrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] CactusGrammarParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CactusGrammarParser.var_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar_name([NotNull] CactusGrammarParser.Var_nameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CactusGrammarParser.var_name"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar_name([NotNull] CactusGrammarParser.Var_nameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CactusGrammarParser.var_dcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVar_dcl([NotNull] CactusGrammarParser.Var_dclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CactusGrammarParser.var_dcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVar_dcl([NotNull] CactusGrammarParser.Var_dclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CactusGrammarParser.assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssign([NotNull] CactusGrammarParser.AssignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CactusGrammarParser.assign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssign([NotNull] CactusGrammarParser.AssignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CactusGrammarParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterValue([NotNull] CactusGrammarParser.ValueContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CactusGrammarParser.value"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitValue([NotNull] CactusGrammarParser.ValueContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CactusGrammarParser.func_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunc_call([NotNull] CactusGrammarParser.Func_callContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CactusGrammarParser.func_call"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunc_call([NotNull] CactusGrammarParser.Func_callContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="CactusGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] CactusGrammarParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="CactusGrammarParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] CactusGrammarParser.ExpressionContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
