//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from c:/BME/sem6/onlab/Builds/build_1/CactusLang/Grammar/CactusGrammar.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="CactusGrammarParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface ICactusGrammarListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="CactusGrammarParser.codefile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCodefile([NotNull] CactusGrammarParser.CodefileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CactusGrammarParser.codefile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCodefile([NotNull] CactusGrammarParser.CodefileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CactusGrammarParser.glob_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGlob_statement([NotNull] CactusGrammarParser.Glob_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CactusGrammarParser.glob_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGlob_statement([NotNull] CactusGrammarParser.Glob_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CactusGrammarParser.prepoc_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrepoc_statement([NotNull] CactusGrammarParser.Prepoc_statementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CactusGrammarParser.prepoc_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrepoc_statement([NotNull] CactusGrammarParser.Prepoc_statementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CactusGrammarParser.func_header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc_header([NotNull] CactusGrammarParser.Func_headerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CactusGrammarParser.func_header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc_header([NotNull] CactusGrammarParser.Func_headerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CactusGrammarParser.func_dcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc_dcl([NotNull] CactusGrammarParser.Func_dclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CactusGrammarParser.func_dcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc_dcl([NotNull] CactusGrammarParser.Func_dclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CactusGrammarParser.field_dcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterField_dcl([NotNull] CactusGrammarParser.Field_dclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CactusGrammarParser.field_dcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitField_dcl([NotNull] CactusGrammarParser.Field_dclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CactusGrammarParser.struct_header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStruct_header([NotNull] CactusGrammarParser.Struct_headerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CactusGrammarParser.struct_header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStruct_header([NotNull] CactusGrammarParser.Struct_headerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CactusGrammarParser.struct_dcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStruct_dcl([NotNull] CactusGrammarParser.Struct_dclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CactusGrammarParser.struct_dcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStruct_dcl([NotNull] CactusGrammarParser.Struct_dclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CactusGrammarParser.code_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCode_body([NotNull] CactusGrammarParser.Code_bodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CactusGrammarParser.code_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCode_body([NotNull] CactusGrammarParser.Code_bodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CactusGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] CactusGrammarParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CactusGrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] CactusGrammarParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CactusGrammarParser.var_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar_name([NotNull] CactusGrammarParser.Var_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CactusGrammarParser.var_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar_name([NotNull] CactusGrammarParser.Var_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CactusGrammarParser.var_dcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVar_dcl([NotNull] CactusGrammarParser.Var_dclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CactusGrammarParser.var_dcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVar_dcl([NotNull] CactusGrammarParser.Var_dclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CactusGrammarParser.assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssign([NotNull] CactusGrammarParser.AssignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CactusGrammarParser.assign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssign([NotNull] CactusGrammarParser.AssignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CactusGrammarParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterValue([NotNull] CactusGrammarParser.ValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CactusGrammarParser.value"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitValue([NotNull] CactusGrammarParser.ValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CactusGrammarParser.func_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc_call([NotNull] CactusGrammarParser.Func_callContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CactusGrammarParser.func_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc_call([NotNull] CactusGrammarParser.Func_callContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="CactusGrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] CactusGrammarParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="CactusGrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] CactusGrammarParser.ExpressionContext context);
}
