//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /mnt/warehouse/BME/sem6/onlab/cactus_project/Builds/build_1/Grammar.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="GrammarParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IGrammarListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.codefile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCodefile([NotNull] GrammarParser.CodefileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.codefile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCodefile([NotNull] GrammarParser.CodefileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.tags"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTags([NotNull] GrammarParser.TagsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.tags"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTags([NotNull] GrammarParser.TagsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.fileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFileStatement([NotNull] GrammarParser.FileStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.fileStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFileStatement([NotNull] GrammarParser.FileStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.preprocessor_stm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPreprocessor_stm([NotNull] GrammarParser.Preprocessor_stmContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.preprocessor_stm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPreprocessor_stm([NotNull] GrammarParser.Preprocessor_stmContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.filepath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFilepath([NotNull] GrammarParser.FilepathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.filepath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFilepath([NotNull] GrammarParser.FilepathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.ppc__Include"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPpc__Include([NotNull] GrammarParser.Ppc__IncludeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.ppc__Include"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPpc__Include([NotNull] GrammarParser.Ppc__IncludeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] GrammarParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] GrammarParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.fileVarDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFileVarDcl([NotNull] GrammarParser.FileVarDclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.fileVarDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFileVarDcl([NotNull] GrammarParser.FileVarDclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.funcDclHeader"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncDclHeader([NotNull] GrammarParser.FuncDclHeaderContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.funcDclHeader"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncDclHeader([NotNull] GrammarParser.FuncDclHeaderContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.funcDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncDcl([NotNull] GrammarParser.FuncDclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.funcDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncDcl([NotNull] GrammarParser.FuncDclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.funcLamdBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncLamdBody([NotNull] GrammarParser.FuncLamdBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.funcLamdBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncLamdBody([NotNull] GrammarParser.FuncLamdBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.returnType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnType([NotNull] GrammarParser.ReturnTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.returnType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnType([NotNull] GrammarParser.ReturnTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParam([NotNull] GrammarParser.ParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParam([NotNull] GrammarParser.ParamContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.paramName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParamName([NotNull] GrammarParser.ParamNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.paramName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParamName([NotNull] GrammarParser.ParamNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.funcName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncName([NotNull] GrammarParser.FuncNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.funcName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncName([NotNull] GrammarParser.FuncNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.varName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarName([NotNull] GrammarParser.VarNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.varName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarName([NotNull] GrammarParser.VarNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.fieldDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFieldDcl([NotNull] GrammarParser.FieldDclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.fieldDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFieldDcl([NotNull] GrammarParser.FieldDclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.structName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructName([NotNull] GrammarParser.StructNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.structName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructName([NotNull] GrammarParser.StructNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.structDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructDcl([NotNull] GrammarParser.StructDclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.structDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructDcl([NotNull] GrammarParser.StructDclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.structBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStructBody([NotNull] GrammarParser.StructBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.structBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStructBody([NotNull] GrammarParser.StructBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.className"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassName([NotNull] GrammarParser.ClassNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.className"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassName([NotNull] GrammarParser.ClassNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.classDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassDcl([NotNull] GrammarParser.ClassDclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.classDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassDcl([NotNull] GrammarParser.ClassDclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.parentClass"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParentClass([NotNull] GrammarParser.ParentClassContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.parentClass"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParentClass([NotNull] GrammarParser.ParentClassContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.interface"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInterface([NotNull] GrammarParser.InterfaceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.interface"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInterface([NotNull] GrammarParser.InterfaceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.interfaces"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInterfaces([NotNull] GrammarParser.InterfacesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.interfaces"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInterfaces([NotNull] GrammarParser.InterfacesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.classBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClassBody([NotNull] GrammarParser.ClassBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.classBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClassBody([NotNull] GrammarParser.ClassBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.codeBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCodeBody([NotNull] GrammarParser.CodeBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.codeBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCodeBody([NotNull] GrammarParser.CodeBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] GrammarParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] GrammarParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.varDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarDcl([NotNull] GrammarParser.VarDclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.varDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarDcl([NotNull] GrammarParser.VarDclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.varDclBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarDclBody([NotNull] GrammarParser.VarDclBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.varDclBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarDclBody([NotNull] GrammarParser.VarDclBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.expressionHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressionHead([NotNull] GrammarParser.ExpressionHeadContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.expressionHead"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressionHead([NotNull] GrammarParser.ExpressionHeadContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.expressionNode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpressionNode([NotNull] GrammarParser.ExpressionNodeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.expressionNode"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpressionNode([NotNull] GrammarParser.ExpressionNodeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.opMultLvl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpMultLvl([NotNull] GrammarParser.OpMultLvlContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.opMultLvl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpMultLvl([NotNull] GrammarParser.OpMultLvlContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.opAddLvl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpAddLvl([NotNull] GrammarParser.OpAddLvlContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.opAddLvl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpAddLvl([NotNull] GrammarParser.OpAddLvlContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.opBitLvl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpBitLvl([NotNull] GrammarParser.OpBitLvlContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.opBitLvl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpBitLvl([NotNull] GrammarParser.OpBitLvlContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.opCompLvl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpCompLvl([NotNull] GrammarParser.OpCompLvlContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.opCompLvl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpCompLvl([NotNull] GrammarParser.OpCompLvlContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.primaryExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimaryExp([NotNull] GrammarParser.PrimaryExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.primaryExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimaryExp([NotNull] GrammarParser.PrimaryExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.opLeftUn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpLeftUn([NotNull] GrammarParser.OpLeftUnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.opLeftUn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpLeftUn([NotNull] GrammarParser.OpLeftUnContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.opRightUn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOpRightUn([NotNull] GrammarParser.OpRightUnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.opRightUn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOpRightUn([NotNull] GrammarParser.OpRightUnContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.primaryExpVal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimaryExpVal([NotNull] GrammarParser.PrimaryExpValContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.primaryExpVal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimaryExpVal([NotNull] GrammarParser.PrimaryExpValContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.parenthsExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenthsExp([NotNull] GrammarParser.ParenthsExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.parenthsExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenthsExp([NotNull] GrammarParser.ParenthsExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.miscPrimeExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMiscPrimeExp([NotNull] GrammarParser.MiscPrimeExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.miscPrimeExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMiscPrimeExp([NotNull] GrammarParser.MiscPrimeExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.alloc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAlloc([NotNull] GrammarParser.AllocContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.alloc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAlloc([NotNull] GrammarParser.AllocContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.free"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFree([NotNull] GrammarParser.FreeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.free"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFree([NotNull] GrammarParser.FreeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.explicitCast"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExplicitCast([NotNull] GrammarParser.ExplicitCastContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.explicitCast"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExplicitCast([NotNull] GrammarParser.ExplicitCastContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] GrammarParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] GrammarParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.funcCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncCall([NotNull] GrammarParser.FuncCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.funcCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncCall([NotNull] GrammarParser.FuncCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.funcParamVals"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncParamVals([NotNull] GrammarParser.FuncParamValsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.funcParamVals"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncParamVals([NotNull] GrammarParser.FuncParamValsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.funcRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncRef([NotNull] GrammarParser.FuncRefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.funcRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncRef([NotNull] GrammarParser.FuncRefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.literalExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteralExp([NotNull] GrammarParser.LiteralExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.literalExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteralExp([NotNull] GrammarParser.LiteralExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.nullLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNullLiteral([NotNull] GrammarParser.NullLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.nullLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNullLiteral([NotNull] GrammarParser.NullLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.numSign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumSign([NotNull] GrammarParser.NumSignContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.numSign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumSign([NotNull] GrammarParser.NumSignContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.numLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumLiteral([NotNull] GrammarParser.NumLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.numLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumLiteral([NotNull] GrammarParser.NumLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.intLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntLiteral([NotNull] GrammarParser.IntLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.intLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntLiteral([NotNull] GrammarParser.IntLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.intDecLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntDecLiteral([NotNull] GrammarParser.IntDecLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.intDecLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntDecLiteral([NotNull] GrammarParser.IntDecLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.intHexLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntHexLiteral([NotNull] GrammarParser.IntHexLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.intHexLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntHexLiteral([NotNull] GrammarParser.IntHexLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.intBinLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntBinLiteral([NotNull] GrammarParser.IntBinLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.intBinLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntBinLiteral([NotNull] GrammarParser.IntBinLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.intOctLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntOctLiteral([NotNull] GrammarParser.IntOctLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.intOctLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntOctLiteral([NotNull] GrammarParser.IntOctLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.floatLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFloatLiteral([NotNull] GrammarParser.FloatLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.floatLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFloatLiteral([NotNull] GrammarParser.FloatLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.strLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStrLiteral([NotNull] GrammarParser.StrLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.strLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStrLiteral([NotNull] GrammarParser.StrLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.charLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCharLiteral([NotNull] GrammarParser.CharLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.charLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCharLiteral([NotNull] GrammarParser.CharLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.boolLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolLiteral([NotNull] GrammarParser.BoolLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.boolLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolLiteral([NotNull] GrammarParser.BoolLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.idPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIdPart([NotNull] GrammarParser.IdPartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.idPart"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIdPart([NotNull] GrammarParser.IdPartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.accOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAccOp([NotNull] GrammarParser.AccOpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.accOp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAccOp([NotNull] GrammarParser.AccOpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.varRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarRef([NotNull] GrammarParser.VarRefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.varRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarRef([NotNull] GrammarParser.VarRefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatement([NotNull] GrammarParser.IfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatement([NotNull] GrammarParser.IfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.elseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseStatement([NotNull] GrammarParser.ElseStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.elseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseStatement([NotNull] GrammarParser.ElseStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStatement([NotNull] GrammarParser.ReturnStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStatement([NotNull] GrammarParser.ReturnStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.continueStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContinueStatement([NotNull] GrammarParser.ContinueStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.continueStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContinueStatement([NotNull] GrammarParser.ContinueStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.breakStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBreakStatement([NotNull] GrammarParser.BreakStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.breakStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBreakStatement([NotNull] GrammarParser.BreakStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.loopDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoopDecl([NotNull] GrammarParser.LoopDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.loopDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoopDecl([NotNull] GrammarParser.LoopDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.loopCond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoopCond([NotNull] GrammarParser.LoopCondContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.loopCond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoopCond([NotNull] GrammarParser.LoopCondContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.endExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEndExp([NotNull] GrammarParser.EndExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.endExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEndExp([NotNull] GrammarParser.EndExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.forLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForLoop([NotNull] GrammarParser.ForLoopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.forLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForLoop([NotNull] GrammarParser.ForLoopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.whileLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileLoop([NotNull] GrammarParser.WhileLoopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.whileLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileLoop([NotNull] GrammarParser.WhileLoopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.ppc__C_Code_Body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPpc__C_Code_Body([NotNull] GrammarParser.Ppc__C_Code_BodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.ppc__C_Code_Body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPpc__C_Code_Body([NotNull] GrammarParser.Ppc__C_Code_BodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.ppc__C_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPpc__C_id([NotNull] GrammarParser.Ppc__C_idContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.ppc__C_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPpc__C_id([NotNull] GrammarParser.Ppc__C_idContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.ppc__C_Func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPpc__C_Func([NotNull] GrammarParser.Ppc__C_FuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.ppc__C_Func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPpc__C_Func([NotNull] GrammarParser.Ppc__C_FuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.ppc__C_Func_Map"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPpc__C_Func_Map([NotNull] GrammarParser.Ppc__C_Func_MapContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.ppc__C_Func_Map"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPpc__C_Func_Map([NotNull] GrammarParser.Ppc__C_Func_MapContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.ppc__varRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPpc__varRef([NotNull] GrammarParser.Ppc__varRefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.ppc__varRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPpc__varRef([NotNull] GrammarParser.Ppc__varRefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.ppc__funcRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPpc__funcRef([NotNull] GrammarParser.Ppc__funcRefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.ppc__funcRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPpc__funcRef([NotNull] GrammarParser.Ppc__funcRefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.ppc__funcCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPpc__funcCall([NotNull] GrammarParser.Ppc__funcCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.ppc__funcCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPpc__funcCall([NotNull] GrammarParser.Ppc__funcCallContext context);
}
