//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /mnt/warehouse/BME/sem6/onlab/cactus_project/Builds/build_1/Grammar.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IGrammarListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class GrammarBaseListener : IGrammarListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.codefile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCodefile([NotNull] GrammarParser.CodefileContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.codefile"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCodefile([NotNull] GrammarParser.CodefileContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.tags"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterTags([NotNull] GrammarParser.TagsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.tags"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitTags([NotNull] GrammarParser.TagsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.fileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFileStatement([NotNull] GrammarParser.FileStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.fileStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFileStatement([NotNull] GrammarParser.FileStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.preprocessor_stm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPreprocessor_stm([NotNull] GrammarParser.Preprocessor_stmContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.preprocessor_stm"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPreprocessor_stm([NotNull] GrammarParser.Preprocessor_stmContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.filepath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFilepath([NotNull] GrammarParser.FilepathContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.filepath"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFilepath([NotNull] GrammarParser.FilepathContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.ppc__Include"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPpc__Include([NotNull] GrammarParser.Ppc__IncludeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.ppc__Include"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPpc__Include([NotNull] GrammarParser.Ppc__IncludeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] GrammarParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] GrammarParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.fileVarDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFileVarDcl([NotNull] GrammarParser.FileVarDclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.fileVarDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFileVarDcl([NotNull] GrammarParser.FileVarDclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.funcDclHeader"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncDclHeader([NotNull] GrammarParser.FuncDclHeaderContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.funcDclHeader"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncDclHeader([NotNull] GrammarParser.FuncDclHeaderContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.funcDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncDcl([NotNull] GrammarParser.FuncDclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.funcDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncDcl([NotNull] GrammarParser.FuncDclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.funcLamdBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncLamdBody([NotNull] GrammarParser.FuncLamdBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.funcLamdBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncLamdBody([NotNull] GrammarParser.FuncLamdBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.returnType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnType([NotNull] GrammarParser.ReturnTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.returnType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnType([NotNull] GrammarParser.ReturnTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.param"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParam([NotNull] GrammarParser.ParamContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.param"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParam([NotNull] GrammarParser.ParamContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.paramName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParamName([NotNull] GrammarParser.ParamNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.paramName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParamName([NotNull] GrammarParser.ParamNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.funcName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncName([NotNull] GrammarParser.FuncNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.funcName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncName([NotNull] GrammarParser.FuncNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.varName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarName([NotNull] GrammarParser.VarNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.varName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarName([NotNull] GrammarParser.VarNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.fieldDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFieldDcl([NotNull] GrammarParser.FieldDclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.fieldDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFieldDcl([NotNull] GrammarParser.FieldDclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.structName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructName([NotNull] GrammarParser.StructNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.structName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructName([NotNull] GrammarParser.StructNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.structDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructDcl([NotNull] GrammarParser.StructDclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.structDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructDcl([NotNull] GrammarParser.StructDclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.structBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStructBody([NotNull] GrammarParser.StructBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.structBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStructBody([NotNull] GrammarParser.StructBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.className"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassName([NotNull] GrammarParser.ClassNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.className"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassName([NotNull] GrammarParser.ClassNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.classDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassDcl([NotNull] GrammarParser.ClassDclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.classDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassDcl([NotNull] GrammarParser.ClassDclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.parentClass"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParentClass([NotNull] GrammarParser.ParentClassContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.parentClass"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParentClass([NotNull] GrammarParser.ParentClassContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.interface"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterface([NotNull] GrammarParser.InterfaceContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.interface"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterface([NotNull] GrammarParser.InterfaceContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.interfaces"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInterfaces([NotNull] GrammarParser.InterfacesContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.interfaces"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInterfaces([NotNull] GrammarParser.InterfacesContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.classBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterClassBody([NotNull] GrammarParser.ClassBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.classBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitClassBody([NotNull] GrammarParser.ClassBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.codeBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCodeBody([NotNull] GrammarParser.CodeBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.codeBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCodeBody([NotNull] GrammarParser.CodeBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStatement([NotNull] GrammarParser.StatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.statement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStatement([NotNull] GrammarParser.StatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.varDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarDcl([NotNull] GrammarParser.VarDclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.varDcl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarDcl([NotNull] GrammarParser.VarDclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.varDclBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarDclBody([NotNull] GrammarParser.VarDclBodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.varDclBody"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarDclBody([NotNull] GrammarParser.VarDclBodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.expressionHead"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionHead([NotNull] GrammarParser.ExpressionHeadContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.expressionHead"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionHead([NotNull] GrammarParser.ExpressionHeadContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.expressionNode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpressionNode([NotNull] GrammarParser.ExpressionNodeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.expressionNode"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpressionNode([NotNull] GrammarParser.ExpressionNodeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.opMultLvl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpMultLvl([NotNull] GrammarParser.OpMultLvlContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.opMultLvl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpMultLvl([NotNull] GrammarParser.OpMultLvlContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.opAddLvl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpAddLvl([NotNull] GrammarParser.OpAddLvlContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.opAddLvl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpAddLvl([NotNull] GrammarParser.OpAddLvlContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.opBitLvl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpBitLvl([NotNull] GrammarParser.OpBitLvlContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.opBitLvl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpBitLvl([NotNull] GrammarParser.OpBitLvlContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.opCompLvl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpCompLvl([NotNull] GrammarParser.OpCompLvlContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.opCompLvl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpCompLvl([NotNull] GrammarParser.OpCompLvlContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.primaryExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimaryExp([NotNull] GrammarParser.PrimaryExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.primaryExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimaryExp([NotNull] GrammarParser.PrimaryExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.opLeftUn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpLeftUn([NotNull] GrammarParser.OpLeftUnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.opLeftUn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpLeftUn([NotNull] GrammarParser.OpLeftUnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.opRightUn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterOpRightUn([NotNull] GrammarParser.OpRightUnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.opRightUn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitOpRightUn([NotNull] GrammarParser.OpRightUnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.primaryExpVal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPrimaryExpVal([NotNull] GrammarParser.PrimaryExpValContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.primaryExpVal"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPrimaryExpVal([NotNull] GrammarParser.PrimaryExpValContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.parenthsExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterParenthsExp([NotNull] GrammarParser.ParenthsExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.parenthsExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitParenthsExp([NotNull] GrammarParser.ParenthsExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.miscPrimeExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMiscPrimeExp([NotNull] GrammarParser.MiscPrimeExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.miscPrimeExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMiscPrimeExp([NotNull] GrammarParser.MiscPrimeExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.alloc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAlloc([NotNull] GrammarParser.AllocContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.alloc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAlloc([NotNull] GrammarParser.AllocContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.free"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFree([NotNull] GrammarParser.FreeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.free"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFree([NotNull] GrammarParser.FreeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.explicitCast"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExplicitCast([NotNull] GrammarParser.ExplicitCastContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.explicitCast"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExplicitCast([NotNull] GrammarParser.ExplicitCastContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAssignment([NotNull] GrammarParser.AssignmentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.assignment"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAssignment([NotNull] GrammarParser.AssignmentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.funcCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncCall([NotNull] GrammarParser.FuncCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.funcCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncCall([NotNull] GrammarParser.FuncCallContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.funcParamVals"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncParamVals([NotNull] GrammarParser.FuncParamValsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.funcParamVals"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncParamVals([NotNull] GrammarParser.FuncParamValsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.funcRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFuncRef([NotNull] GrammarParser.FuncRefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.funcRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFuncRef([NotNull] GrammarParser.FuncRefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.literalExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLiteralExp([NotNull] GrammarParser.LiteralExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.literalExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLiteralExp([NotNull] GrammarParser.LiteralExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.nullLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNullLiteral([NotNull] GrammarParser.NullLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.nullLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNullLiteral([NotNull] GrammarParser.NullLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.numSign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumSign([NotNull] GrammarParser.NumSignContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.numSign"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumSign([NotNull] GrammarParser.NumSignContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.numLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumLiteral([NotNull] GrammarParser.NumLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.numLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumLiteral([NotNull] GrammarParser.NumLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.intLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntLiteral([NotNull] GrammarParser.IntLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.intLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntLiteral([NotNull] GrammarParser.IntLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.intDecLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntDecLiteral([NotNull] GrammarParser.IntDecLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.intDecLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntDecLiteral([NotNull] GrammarParser.IntDecLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.intHexLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntHexLiteral([NotNull] GrammarParser.IntHexLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.intHexLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntHexLiteral([NotNull] GrammarParser.IntHexLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.intBinLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntBinLiteral([NotNull] GrammarParser.IntBinLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.intBinLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntBinLiteral([NotNull] GrammarParser.IntBinLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.intOctLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIntOctLiteral([NotNull] GrammarParser.IntOctLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.intOctLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIntOctLiteral([NotNull] GrammarParser.IntOctLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.floatLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFloatLiteral([NotNull] GrammarParser.FloatLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.floatLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFloatLiteral([NotNull] GrammarParser.FloatLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.strLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStrLiteral([NotNull] GrammarParser.StrLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.strLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStrLiteral([NotNull] GrammarParser.StrLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.charLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCharLiteral([NotNull] GrammarParser.CharLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.charLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCharLiteral([NotNull] GrammarParser.CharLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.boolLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolLiteral([NotNull] GrammarParser.BoolLiteralContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.boolLiteral"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolLiteral([NotNull] GrammarParser.BoolLiteralContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.idPart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIdPart([NotNull] GrammarParser.IdPartContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.idPart"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIdPart([NotNull] GrammarParser.IdPartContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.accOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAccOp([NotNull] GrammarParser.AccOpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.accOp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAccOp([NotNull] GrammarParser.AccOpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.varRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVarRef([NotNull] GrammarParser.VarRefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.varRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVarRef([NotNull] GrammarParser.VarRefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterIfStatement([NotNull] GrammarParser.IfStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.ifStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitIfStatement([NotNull] GrammarParser.IfStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.elseStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterElseStatement([NotNull] GrammarParser.ElseStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.elseStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitElseStatement([NotNull] GrammarParser.ElseStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterReturnStatement([NotNull] GrammarParser.ReturnStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.returnStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitReturnStatement([NotNull] GrammarParser.ReturnStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.continueStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterContinueStatement([NotNull] GrammarParser.ContinueStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.continueStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitContinueStatement([NotNull] GrammarParser.ContinueStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.breakStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBreakStatement([NotNull] GrammarParser.BreakStatementContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.breakStatement"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBreakStatement([NotNull] GrammarParser.BreakStatementContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.loopDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoopDecl([NotNull] GrammarParser.LoopDeclContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.loopDecl"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoopDecl([NotNull] GrammarParser.LoopDeclContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.loopCond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterLoopCond([NotNull] GrammarParser.LoopCondContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.loopCond"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitLoopCond([NotNull] GrammarParser.LoopCondContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.endExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterEndExp([NotNull] GrammarParser.EndExpContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.endExp"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitEndExp([NotNull] GrammarParser.EndExpContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.forLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterForLoop([NotNull] GrammarParser.ForLoopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.forLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitForLoop([NotNull] GrammarParser.ForLoopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.whileLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterWhileLoop([NotNull] GrammarParser.WhileLoopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.whileLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitWhileLoop([NotNull] GrammarParser.WhileLoopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.ppc__C_Code_Body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPpc__C_Code_Body([NotNull] GrammarParser.Ppc__C_Code_BodyContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.ppc__C_Code_Body"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPpc__C_Code_Body([NotNull] GrammarParser.Ppc__C_Code_BodyContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.ppc__C_id"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPpc__C_id([NotNull] GrammarParser.Ppc__C_idContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.ppc__C_id"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPpc__C_id([NotNull] GrammarParser.Ppc__C_idContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.ppc__C_Func"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPpc__C_Func([NotNull] GrammarParser.Ppc__C_FuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.ppc__C_Func"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPpc__C_Func([NotNull] GrammarParser.Ppc__C_FuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.ppc__C_Func_Map"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPpc__C_Func_Map([NotNull] GrammarParser.Ppc__C_Func_MapContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.ppc__C_Func_Map"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPpc__C_Func_Map([NotNull] GrammarParser.Ppc__C_Func_MapContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.ppc__varRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPpc__varRef([NotNull] GrammarParser.Ppc__varRefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.ppc__varRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPpc__varRef([NotNull] GrammarParser.Ppc__varRefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.ppc__funcRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPpc__funcRef([NotNull] GrammarParser.Ppc__funcRefContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.ppc__funcRef"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPpc__funcRef([NotNull] GrammarParser.Ppc__funcRefContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.ppc__funcCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterPpc__funcCall([NotNull] GrammarParser.Ppc__funcCallContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.ppc__funcCall"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitPpc__funcCall([NotNull] GrammarParser.Ppc__funcCallContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
