//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from /mnt/warehouse/BME/sem6/onlab/cactus_project/Builds/build_1/Grammar.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="GrammarParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IGrammarVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.codefile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCodefile([NotNull] GrammarParser.CodefileContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.tags"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTags([NotNull] GrammarParser.TagsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.globStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitGlobStatement([NotNull] GrammarParser.GlobStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.preprocessor_stm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPreprocessor_stm([NotNull] GrammarParser.Preprocessor_stmContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.filepath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFilepath([NotNull] GrammarParser.FilepathContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.ppc__Include"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPpc__Include([NotNull] GrammarParser.Ppc__IncludeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.ptrLvl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPtrLvl([NotNull] GrammarParser.PtrLvlContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] GrammarParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.funcDclHeader"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncDclHeader([NotNull] GrammarParser.FuncDclHeaderContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.funcDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncDcl([NotNull] GrammarParser.FuncDclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.funcLamdBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncLamdBody([NotNull] GrammarParser.FuncLamdBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.returnType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnType([NotNull] GrammarParser.ReturnTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParam([NotNull] GrammarParser.ParamContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.paramName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParamName([NotNull] GrammarParser.ParamNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.funcName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncName([NotNull] GrammarParser.FuncNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.varName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarName([NotNull] GrammarParser.VarNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.fieldDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFieldDcl([NotNull] GrammarParser.FieldDclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.structName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructName([NotNull] GrammarParser.StructNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.structDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructDcl([NotNull] GrammarParser.StructDclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.structBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStructBody([NotNull] GrammarParser.StructBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.className"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassName([NotNull] GrammarParser.ClassNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.classDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassDcl([NotNull] GrammarParser.ClassDclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.parentClass"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParentClass([NotNull] GrammarParser.ParentClassContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.interface"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterface([NotNull] GrammarParser.InterfaceContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.interfaces"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterfaces([NotNull] GrammarParser.InterfacesContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.classBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitClassBody([NotNull] GrammarParser.ClassBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.codeBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCodeBody([NotNull] GrammarParser.CodeBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] GrammarParser.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.varDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarDcl([NotNull] GrammarParser.VarDclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.varDclBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarDclBody([NotNull] GrammarParser.VarDclBodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] GrammarParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.opMultLvl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpMultLvl([NotNull] GrammarParser.OpMultLvlContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.opAddLvl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpAddLvl([NotNull] GrammarParser.OpAddLvlContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.opBitLvl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpBitLvl([NotNull] GrammarParser.OpBitLvlContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.opCompLvl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpCompLvl([NotNull] GrammarParser.OpCompLvlContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.primaryExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryExp([NotNull] GrammarParser.PrimaryExpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.opLeftUn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpLeftUn([NotNull] GrammarParser.OpLeftUnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.opRightUn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitOpRightUn([NotNull] GrammarParser.OpRightUnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.primaryExpVal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimaryExpVal([NotNull] GrammarParser.PrimaryExpValContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.parenthsExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParenthsExp([NotNull] GrammarParser.ParenthsExpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.miscPrimeExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMiscPrimeExp([NotNull] GrammarParser.MiscPrimeExpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.alloc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAlloc([NotNull] GrammarParser.AllocContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.free"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFree([NotNull] GrammarParser.FreeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.explicitCast"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExplicitCast([NotNull] GrammarParser.ExplicitCastContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment([NotNull] GrammarParser.AssignmentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.funcCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncCall([NotNull] GrammarParser.FuncCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.funcParamVals"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncParamVals([NotNull] GrammarParser.FuncParamValsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.funcRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFuncRef([NotNull] GrammarParser.FuncRefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.literalExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLiteralExp([NotNull] GrammarParser.LiteralExpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.nullLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNullLiteral([NotNull] GrammarParser.NullLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.numSign"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumSign([NotNull] GrammarParser.NumSignContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.numLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNumLiteral([NotNull] GrammarParser.NumLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.intLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntLiteral([NotNull] GrammarParser.IntLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.intDecLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntDecLiteral([NotNull] GrammarParser.IntDecLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.intHexLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntHexLiteral([NotNull] GrammarParser.IntHexLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.intBinLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntBinLiteral([NotNull] GrammarParser.IntBinLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.intOctLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIntOctLiteral([NotNull] GrammarParser.IntOctLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.floatLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFloatLiteral([NotNull] GrammarParser.FloatLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.strLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStrLiteral([NotNull] GrammarParser.StrLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.charLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCharLiteral([NotNull] GrammarParser.CharLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.boolLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolLiteral([NotNull] GrammarParser.BoolLiteralContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.varRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVarRef([NotNull] GrammarParser.VarRefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIfStatement([NotNull] GrammarParser.IfStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.elseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitElseStatement([NotNull] GrammarParser.ElseStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitReturnStatement([NotNull] GrammarParser.ReturnStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.continueStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitContinueStatement([NotNull] GrammarParser.ContinueStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.breakStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBreakStatement([NotNull] GrammarParser.BreakStatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.loopDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoopDecl([NotNull] GrammarParser.LoopDeclContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.loopCond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLoopCond([NotNull] GrammarParser.LoopCondContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.endExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitEndExp([NotNull] GrammarParser.EndExpContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.forLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitForLoop([NotNull] GrammarParser.ForLoopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.whileLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitWhileLoop([NotNull] GrammarParser.WhileLoopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.ppc__C_Code_Body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPpc__C_Code_Body([NotNull] GrammarParser.Ppc__C_Code_BodyContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.ppc__C_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPpc__C_id([NotNull] GrammarParser.Ppc__C_idContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.ppc__C_Func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPpc__C_Func([NotNull] GrammarParser.Ppc__C_FuncContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.ppc__C_Func_Map"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPpc__C_Func_Map([NotNull] GrammarParser.Ppc__C_Func_MapContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.ppc__varRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPpc__varRef([NotNull] GrammarParser.Ppc__varRefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.ppc__funcRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPpc__funcRef([NotNull] GrammarParser.Ppc__funcRefContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.ppc__funcCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPpc__funcCall([NotNull] GrammarParser.Ppc__funcCallContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GrammarParser.ppc__Token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPpc__Token([NotNull] GrammarParser.Ppc__TokenContext context);
}
