//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from d:/ARCHIVE/BME/sem6/onlab/cactus_project/Builds/build_1/CactusLang/Cactus/Grammar.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="GrammarParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public interface IGrammarListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.codefile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCodefile([NotNull] GrammarParser.CodefileContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.codefile"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCodefile([NotNull] GrammarParser.CodefileContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.tags"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterTags([NotNull] GrammarParser.TagsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.tags"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitTags([NotNull] GrammarParser.TagsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.globStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterGlobStatement([NotNull] GrammarParser.GlobStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.globStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitGlobStatement([NotNull] GrammarParser.GlobStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.preprocessor_stm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPreprocessor_stm([NotNull] GrammarParser.Preprocessor_stmContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.preprocessor_stm"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPreprocessor_stm([NotNull] GrammarParser.Preprocessor_stmContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.filepath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFilepath([NotNull] GrammarParser.FilepathContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.filepath"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFilepath([NotNull] GrammarParser.FilepathContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.ppc__Include"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPpc__Include([NotNull] GrammarParser.Ppc__IncludeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.ppc__Include"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPpc__Include([NotNull] GrammarParser.Ppc__IncludeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.ptrLvl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPtrLvl([NotNull] GrammarParser.PtrLvlContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.ptrLvl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPtrLvl([NotNull] GrammarParser.PtrLvlContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] GrammarParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] GrammarParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.func_dcl_header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc_dcl_header([NotNull] GrammarParser.Func_dcl_headerContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.func_dcl_header"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc_dcl_header([NotNull] GrammarParser.Func_dcl_headerContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.func_dcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc_dcl([NotNull] GrammarParser.Func_dclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.func_dcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc_dcl([NotNull] GrammarParser.Func_dclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.func_lamd_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunc_lamd_body([NotNull] GrammarParser.Func_lamd_bodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.func_lamd_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunc_lamd_body([NotNull] GrammarParser.Func_lamd_bodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.returnType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnType([NotNull] GrammarParser.ReturnTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.returnType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnType([NotNull] GrammarParser.ReturnTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParam([NotNull] GrammarParser.ParamContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.param"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParam([NotNull] GrammarParser.ParamContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.funcName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncName([NotNull] GrammarParser.FuncNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.funcName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncName([NotNull] GrammarParser.FuncNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.varName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarName([NotNull] GrammarParser.VarNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.varName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarName([NotNull] GrammarParser.VarNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.field_dcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterField_dcl([NotNull] GrammarParser.Field_dclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.field_dcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitField_dcl([NotNull] GrammarParser.Field_dclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.struct_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStruct_name([NotNull] GrammarParser.Struct_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.struct_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStruct_name([NotNull] GrammarParser.Struct_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.struct_dcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStruct_dcl([NotNull] GrammarParser.Struct_dclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.struct_dcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStruct_dcl([NotNull] GrammarParser.Struct_dclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.struct_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStruct_body([NotNull] GrammarParser.Struct_bodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.struct_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStruct_body([NotNull] GrammarParser.Struct_bodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.class_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClass_name([NotNull] GrammarParser.Class_nameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.class_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClass_name([NotNull] GrammarParser.Class_nameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.class_dcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClass_dcl([NotNull] GrammarParser.Class_dclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.class_dcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClass_dcl([NotNull] GrammarParser.Class_dclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.parent_class"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParent_class([NotNull] GrammarParser.Parent_classContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.parent_class"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParent_class([NotNull] GrammarParser.Parent_classContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.interface"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInterface([NotNull] GrammarParser.InterfaceContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.interface"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInterface([NotNull] GrammarParser.InterfaceContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.interfaces"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInterfaces([NotNull] GrammarParser.InterfacesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.interfaces"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInterfaces([NotNull] GrammarParser.InterfacesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.class_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterClass_body([NotNull] GrammarParser.Class_bodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.class_body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitClass_body([NotNull] GrammarParser.Class_bodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.codeBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCodeBody([NotNull] GrammarParser.CodeBodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.codeBody"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCodeBody([NotNull] GrammarParser.CodeBodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStatement([NotNull] GrammarParser.StatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStatement([NotNull] GrammarParser.StatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.varDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarDcl([NotNull] GrammarParser.VarDclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.varDcl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarDcl([NotNull] GrammarParser.VarDclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] GrammarParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] GrammarParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.op_MultLvl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_MultLvl([NotNull] GrammarParser.Op_MultLvlContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.op_MultLvl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_MultLvl([NotNull] GrammarParser.Op_MultLvlContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.op_AddLvl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_AddLvl([NotNull] GrammarParser.Op_AddLvlContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.op_AddLvl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_AddLvl([NotNull] GrammarParser.Op_AddLvlContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.op_BitLvl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_BitLvl([NotNull] GrammarParser.Op_BitLvlContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.op_BitLvl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_BitLvl([NotNull] GrammarParser.Op_BitLvlContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.op_CompLvl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_CompLvl([NotNull] GrammarParser.Op_CompLvlContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.op_CompLvl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_CompLvl([NotNull] GrammarParser.Op_CompLvlContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.primaryExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimaryExp([NotNull] GrammarParser.PrimaryExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.primaryExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimaryExp([NotNull] GrammarParser.PrimaryExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.op_lUn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_lUn([NotNull] GrammarParser.Op_lUnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.op_lUn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_lUn([NotNull] GrammarParser.Op_lUnContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.op_rUn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterOp_rUn([NotNull] GrammarParser.Op_rUnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.op_rUn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitOp_rUn([NotNull] GrammarParser.Op_rUnContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.primaryExpVal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimaryExpVal([NotNull] GrammarParser.PrimaryExpValContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.primaryExpVal"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimaryExpVal([NotNull] GrammarParser.PrimaryExpValContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.parenthsExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParenthsExp([NotNull] GrammarParser.ParenthsExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.parenthsExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParenthsExp([NotNull] GrammarParser.ParenthsExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.miscPrimeExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMiscPrimeExp([NotNull] GrammarParser.MiscPrimeExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.miscPrimeExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMiscPrimeExp([NotNull] GrammarParser.MiscPrimeExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.alloc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAlloc([NotNull] GrammarParser.AllocContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.alloc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAlloc([NotNull] GrammarParser.AllocContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.free"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFree([NotNull] GrammarParser.FreeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.free"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFree([NotNull] GrammarParser.FreeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.explicitCast"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExplicitCast([NotNull] GrammarParser.ExplicitCastContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.explicitCast"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExplicitCast([NotNull] GrammarParser.ExplicitCastContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] GrammarParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.assignment"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] GrammarParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.funcCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncCall([NotNull] GrammarParser.FuncCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.funcCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncCall([NotNull] GrammarParser.FuncCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.funcParamVals"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncParamVals([NotNull] GrammarParser.FuncParamValsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.funcParamVals"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncParamVals([NotNull] GrammarParser.FuncParamValsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.funcRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFuncRef([NotNull] GrammarParser.FuncRefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.funcRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFuncRef([NotNull] GrammarParser.FuncRefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.literalExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLiteralExp([NotNull] GrammarParser.LiteralExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.literalExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLiteralExp([NotNull] GrammarParser.LiteralExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.nullLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNullLiteral([NotNull] GrammarParser.NullLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.nullLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNullLiteral([NotNull] GrammarParser.NullLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.numLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNumLiteral([NotNull] GrammarParser.NumLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.numLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNumLiteral([NotNull] GrammarParser.NumLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.intLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntLiteral([NotNull] GrammarParser.IntLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.intLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntLiteral([NotNull] GrammarParser.IntLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.intDecLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntDecLiteral([NotNull] GrammarParser.IntDecLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.intDecLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntDecLiteral([NotNull] GrammarParser.IntDecLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.intHexLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntHexLiteral([NotNull] GrammarParser.IntHexLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.intHexLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntHexLiteral([NotNull] GrammarParser.IntHexLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.intBinLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntBinLiteral([NotNull] GrammarParser.IntBinLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.intBinLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntBinLiteral([NotNull] GrammarParser.IntBinLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.intOctLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIntOctLiteral([NotNull] GrammarParser.IntOctLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.intOctLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIntOctLiteral([NotNull] GrammarParser.IntOctLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.floatLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFloatLiteral([NotNull] GrammarParser.FloatLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.floatLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFloatLiteral([NotNull] GrammarParser.FloatLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.strLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStrLiteral([NotNull] GrammarParser.StrLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.strLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStrLiteral([NotNull] GrammarParser.StrLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.charLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCharLiteral([NotNull] GrammarParser.CharLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.charLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCharLiteral([NotNull] GrammarParser.CharLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.boolLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolLiteral([NotNull] GrammarParser.BoolLiteralContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.boolLiteral"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolLiteral([NotNull] GrammarParser.BoolLiteralContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.varRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVarRef([NotNull] GrammarParser.VarRefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.varRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVarRef([NotNull] GrammarParser.VarRefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIfStatement([NotNull] GrammarParser.IfStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.ifStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIfStatement([NotNull] GrammarParser.IfStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.elseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterElseStatement([NotNull] GrammarParser.ElseStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.elseStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitElseStatement([NotNull] GrammarParser.ElseStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturnStatement([NotNull] GrammarParser.ReturnStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.returnStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturnStatement([NotNull] GrammarParser.ReturnStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.continueStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContinueStatement([NotNull] GrammarParser.ContinueStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.continueStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContinueStatement([NotNull] GrammarParser.ContinueStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.breakStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBreakStatement([NotNull] GrammarParser.BreakStatementContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.breakStatement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBreakStatement([NotNull] GrammarParser.BreakStatementContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.loopDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoopDecl([NotNull] GrammarParser.LoopDeclContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.loopDecl"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoopDecl([NotNull] GrammarParser.LoopDeclContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.loopCond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLoopCond([NotNull] GrammarParser.LoopCondContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.loopCond"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLoopCond([NotNull] GrammarParser.LoopCondContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.endExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEndExp([NotNull] GrammarParser.EndExpContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.endExp"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEndExp([NotNull] GrammarParser.EndExpContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.forLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterForLoop([NotNull] GrammarParser.ForLoopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.forLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitForLoop([NotNull] GrammarParser.ForLoopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.whileLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhileLoop([NotNull] GrammarParser.WhileLoopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.whileLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhileLoop([NotNull] GrammarParser.WhileLoopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.ppc__C_Code_Body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPpc__C_Code_Body([NotNull] GrammarParser.Ppc__C_Code_BodyContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.ppc__C_Code_Body"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPpc__C_Code_Body([NotNull] GrammarParser.Ppc__C_Code_BodyContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.ppc__C_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPpc__C_id([NotNull] GrammarParser.Ppc__C_idContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.ppc__C_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPpc__C_id([NotNull] GrammarParser.Ppc__C_idContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.ppc__C_Func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPpc__C_Func([NotNull] GrammarParser.Ppc__C_FuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.ppc__C_Func"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPpc__C_Func([NotNull] GrammarParser.Ppc__C_FuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.ppc__C_Func_Map"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPpc__C_Func_Map([NotNull] GrammarParser.Ppc__C_Func_MapContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.ppc__C_Func_Map"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPpc__C_Func_Map([NotNull] GrammarParser.Ppc__C_Func_MapContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.ppc__varRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPpc__varRef([NotNull] GrammarParser.Ppc__varRefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.ppc__varRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPpc__varRef([NotNull] GrammarParser.Ppc__varRefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.ppc__funcRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPpc__funcRef([NotNull] GrammarParser.Ppc__funcRefContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.ppc__funcRef"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPpc__funcRef([NotNull] GrammarParser.Ppc__funcRefContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.ppc__funcCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPpc__funcCall([NotNull] GrammarParser.Ppc__funcCallContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.ppc__funcCall"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPpc__funcCall([NotNull] GrammarParser.Ppc__funcCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="GrammarParser.ppc__Token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPpc__Token([NotNull] GrammarParser.Ppc__TokenContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="GrammarParser.ppc__Token"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPpc__Token([NotNull] GrammarParser.Ppc__TokenContext context);
}
